# Generated by Django 3.1.2 on 2021-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordev', '0003_auto_20210216_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(upload_to='', verbose_name=''),
        ),
    ]
